CREATE TABLE Person (
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        username varchar(100) NOT NULL,
                        birth_year int NOT NULL,
                        password varchar NOT NULL
);

INSERT INTO Person (username, birth_year, password) VALUES ('user1', 2000, 'password1');
INSERT INTO Person (username, birth_year, password) VALUES ('user2', 1990, 'password2');